is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.ruleTaxYearNotSupported
displayName: Delete Pension Charges
description: This endpoint allows a developer to delete charges relating to pensions. A National Insurance number and tax year must be provided.
(annotations.sandboxData): !include scenarios/deletePensionCharges.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  204:
      headers:
        X-CorrelationId:
          example: c75f40a6-a3df-4429-a697-471eeec46435
          description: Unique ID for operation tracking <br> String, 36 characters.