is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatTypeOfBusiness
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFoundNino
  - queryParameters.taxYear
  - queryParameters.typeOfBusiness
displayName: Retrieve a UK Property Business Income Source Summary (BISS)
description: This endpoint allows a developer to retrieve a running year-to-date (YTD) summary of the income and expenditure for a specified UK property business during a tax year.
(annotations.sandboxData): !include scenarios/retrieveUkPropBiss.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieveBiss/retrieve_uk_property_response.json
        examples:
          example-1:
            description: UK Property Summary FHL
            value: !include examples/retrieveUkPropertyBiss/retrieve_fhl_response.json
          example-2:
            description: UK Property Summary Non FHL
            value: !include examples/retrieveUkPropertyBiss/retrieve_non_fhl_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
